name: "Setup environment"
description: "Setup for node, pnpm and cache"

runs:
  using: composite
  steps:
    - name: "Install pnpm"
      uses: pnpm/action-setup@v4

    - name: "Set node version to v22"
      uses: "actions/setup-node@v4"
      with:
        node-version: "22"
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org/"
