name: "Publish package"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: "./.github/actions/setup"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: "Build"
        run: pnpm run build

      - name: "Publish to npm"
        run: pnpm run publish-ci ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Generate changelog"
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
